### ISSUE TITLE
Questbook is Empty

### ISSUE THREAD

**Issue by WynterFoxx** [rgtexa/Automaton#9] opened 2018-02-12 05:24 UTC
Questbook is empty for all players even when reloading quests. The solution I found is by enabling editing for myself using commands, saving the database default, and then disabling editing.

**Comment by rgtexa** [comment] 2018-03-10 19:46
I've never experienced this issue and have been unable to replicate.

I've verified that all of the downloads for the pack have the default quest database in the download, and have tried several fresh installs of the pack with several new worlds each and have never seen an empty questbook.

What platform are you running Minecraft on?

Are you playing the pack through the Twitch client or another client?

Are you using the native or Jar launcher for Minecraft?

What options are you using when creating your world?

**Comment by WynterFoxx** [comment] 2018-03-10 21:00
Well everyone who plays your modpack has these issues. I play on Windows
10, Twitch client, I used both launchers, and I used default options for my
world.

**Comment by rgtexa** [comment] 2018-03-10 21:29
I've seen a few comments about missing quests, but for most users, a reload of the database fixes it. This is the first report I've seen of anyone needing to re-save the database and reload it.

Have you experienced this issue with other packs that use Better Questing in 1.12.2 (for example, Forever Stranded Lost Souls)?

Have you added/removed any mods to/from the pack?

Have you updated any mods included in the pack?

**Comment by WynterFoxx** [comment] 2018-03-10 22:02
Not with any other modpacks, and I haven't added any conflicting mods.

**Comment by rgtexa** [comment] 2018-03-10 22:45
So, what mods have you added?

You are careful to say you added no _conflicting_ mods, not that you added _no mods_, but if there are mods added that are not part of the default pack install, I can't very well determine why you have a blank quest book unless I can test with the pack in the same state you are using it in. I've done as much testing as I can with the default pack release and can't reproduce this blank quest book issue.

I want to fix this if there is a problem to fix, but I need information and I need to know exactly what's different between the default pack release and what you are doing.

**Comment by WynterFoxx** [comment] 2018-03-10 23:22
Tails Mod 1.12.2 (surprise surprise), and Optifine HD U C8 (no shaders in use)

Perhaps it would work better if you downloaded the modpack from the Twitch client to test it, in case there are differences between release and your own copy? (if you don't already do that already, which you probably do..)

**Comment by rgtexa** [comment] 2018-03-11 02:33
I did start today by downloading a fresh copy from Twitch and didn't see the issue. I also usually keep 2 instances - one I use for development and one that is a straight install of the version on Twitch.

I also just created a new instance (fresh download) and added Tails and Optifine and didn't experience the blank quest book issue either so it doesn't appear that either of them are causing the issue (at least with the default settings).

Had you experienced this issue before adding these mods? If you installed these before running the pack the first time, would it be possible for you to create a fresh instance without them and verify if you are still experiencing the blank quest book issue? Unfortunately, there are too many settings within Optifine for me to try and debug them all in the pack to see if there might be one that is potentially conflicting with Better Questing.

There are several bugs opened on the Better Questing Github related to a blank quest book, such as [this one](https://github.com/Funwayguy/BetterQuesting/issues/308), but there doesn't seem to be any resolution.

One of the bugs might have something though - can you verify you have the Standard Expansion mod present in your mods folder? This mod is needed to ensure the quest book actually has content, and while it is included in the pack, something may have gone wrong with your download (it should be version 2.4.134 and Better Questing should be version 2.5.236).

If that's there, then I would suggest updating the pack to the newest version. I just uploaded a beta of 1.2.0 of the pack this morning and it includes newer (beta) versions of Better Questing (version 3 now whereas the 1.1.0 version of the pack is on Better Questing 2) and it's largely been re-written, so it may have corrected whatever bug you are experiencing.

**Comment by Voxel-Friend** [comment] 2018-03-12 05:37
If I might chime in, With the 1.1.0 version of the pack, quests are there, just off screen. if people would actually attempt to futz with it for a few seconds, that would discover that they can just zoom out and scroll the quest window to the right, thus revealing the quests to the top left. This issue can be closed, however, as when using the new beta version of the pack(1.2.0), the quest book opens right onto the quests properly.

**Comment by digitalight** [comment] 2018-04-21 15:53
Downloaded version 1.1 using MultiMC 5 and was seeing the problem of no quests.
Downloaded and new instance of version 1.2 beta and the problem goes away so it is related to version 1.1

**Comment by szkuwa** [comment] 2018-04-23 23:03
I'm using 1.1.0 beta from Twitch and had a problem with "missing" quests - the left menu was OK but quest side where icons should be was empty. Reloading or re-saving did not help.

After some tinkering (zooming out, scrolling) I've found out that the quest icons were hidden outside of the view box - way to the left.

First I've manually changed `DefaultQuests.json` file and set quest `x` position from `-366` to positive number and it did the trick. Then I've used simple php script to offset all quests `x`'s and whole quest book is working as intended now.

Not sure if it is related to bug that others are experiencing but hope it helps.

[This is the script that I've used](https://pastebin.com/TH7yjFJ0) - nothing complicated
and [here is DefaultQuests.txt](https://github.com/rgtexa/Automaton/files/1940305/DefaultQuests-fixed.txt) with fixed `x` positions

**Comment by IsLilyYaGirl** [comment] 2018-05-19 15:40
same issue here, the quests are just ALL THE WAY to the left. (EDIT: on 1.1.0)

**Comment by IsLilyYaGirl** [comment] 2018-05-19 15:56
Gonna download the new one

**Comment by IsLilyYaGirl** [comment] 2018-05-19 17:00
The new one has no problems!

**Comment by rgtexa** [comment] 2018-07-01 01:44
This issue appears fixed in 1.3.0.

**Closed as completed by rgtexa** 2018-07-01 01:44 UTC
Labels: can't reproduce
